### ISSUE TITLE
Problem with timezone for Israel

### ISSUE THREAD

**Issue by pshotts** [dylandoamaral/trakt-integration#121]
Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 10:08:15 (1 occurrences)
Last logged: 10:08:15

Detected blocking call to open with args ('/usr/local/lib/python3.12/site-packages/pytz/zoneinfo/Asia/Tel_Aviv', 'rb') inside the event loop by custom integration 'trakt_tv' at custom_components/trakt_tv/apis/trakt.py, line 303: timezoned_now = datetime.now(pytz.timezone(configuration.get_timezone())) (offender: /usr/local/lib/python3.12/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please create a bug report at https://github.com/dylandoamaral/trakt-integration/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/config/custom_components/trakt_tv/apis/trakt.py", line 303, in fetch_upcoming timezoned_now = datetime.now(pytz.timezone(configuration.get_timezone()))

**Comment by dylandoamaral** [comment]
The timezone do exist I don't know what is going on: https://gist.github.com/heyalexej/8bf688fd67d7199be4a1682b3eec7568. Sorry but it is not due to our code.
