### ISSUE TITLE
Unable to complete auth process even with @blizzrdof77 and @robloh workaround

### ISSUE THREAD

**Issue by kirub** [dylandoamaral/trakt-integration#124]
Tried both the normal (Prepare Trakt) way and the workaround and got further with the workaround. I got to the trackt authorize page then the home assistant link page but that redirected me to the https://my.home-assistant.io/create-link/?redirect=oauth page with (sometimes) an "invalid parameters" popup.
The integration stay stuck for a while on the "Loading next step for Trackt".

trackt authorize page
![image](https://github.com/user-attachments/assets/50658c66-9f73-4cd1-b1bb-54e328f4e761)

Home assistant link page: https://my.home-assistant.io/redirect/oauth/?code=.........
![image](https://github.com/user-attachments/assets/47dd4b08-39ee-4851-90ef-31bcb36b4742)

Loading next step for Trackt
![image](https://github.com/user-attachments/assets/6eed7f6d-6f56-4b1f-987c-a6fb0ee9065b)

Also noticed that I get the same issue directly going to: 
https://my.home-assistant.io/redirect/oauth
![image](https://github.com/user-attachments/assets/3449f64f-62b7-4dc3-a81e-74df99e9b43b)

Logs from home assistant:

Logger: homeassistant.config_entries
Source: config_entries.py:635
First occurred: 22:30:43 (2 occurrences)
Last logged: 22:34:06

Error setting up entry Trakt for trakt_tv
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/trakt_tv/__init__.py", line 64, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 309, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 279, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 519, in retrieve_data
    sources_data = await gather(*coroutine_sources_data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 316, in fetch_next_to_watch
    data = await self.fetch_upcoming(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 268, in fetch_upcoming
    raw_medias = await self.fetch_watched(excluded_shows, not only_upcoming)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 149, in fetch_watched
    hidden_items = await self.request(
                   ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 97, in request
    await self.retry_request(300, response, method, url, retry, **kwargs)
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 60, in retry_request
    await sleep(wait_time)
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 665, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

**Comment by tunisiano187** [comment]
Same problem
