### ISSUE TITLE
Time data does not match format.

### ISSUE THREAD

**Issue by TNTPro** [dylandoamaral/trakt-integration#36]
Hi,

Firstly, thanks for the integration.
Latest update give me an error:

This error originated from a custom integration.

Logger: custom_components.trakt_tv
Source: custom_components/trakt_tv/models/media.py:111
Integration: Trakt (documentation, issues)
First occurred: 20:50:50 (5 occurrences)
Last logged: 20:52:10

Unexpected error fetching trakt data: time data '2022-05-14' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
Unexpected error fetching trakt data: time data '2022-05-17' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 145, in retrieve_data
    data = await gather(
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 110, in fetch_upcomings
    data = await gather(
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 103, in fetch_upcoming
    medias = [trakt_kind.value.model.from_trakt(media) for media in raw_medias]
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 103, in <listcomp>
    medias = [trakt_kind.value.model.from_trakt(media) for media in raw_medias]
  File "/config/custom_components/trakt_tv/models/media.py", line 111, in from_trakt
    datetime.strptime(data["released"], UPCOMING_DATA_FORMAT)
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-05-14' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'

I didn't notice this on previous version.

**Comment by mimuncito** [comment]
I have exactly the same problem.

**Comment by Amerigo1973** [comment]
![Trouble Trakt](https://user-images.githubusercontent.com/76919269/168480063-6d8e4ad3-85f3-49a8-9481-626f8114d9bd.JPG)

**Comment by dylandoamaral** [comment]
I will fix it ASAP

**Comment by dylandoamaral** [comment]
Release 0.3.4 should fix the issue.

**Comment by TNTPro** [comment]
Thanks for the prompt fix.  Unfortunately, I now have a new error.

This error originated from a custom integration.

Logger: custom_components.trakt_tv
Source: custom_components/trakt_tv/models/media.py:115
Integration: Trakt (documentation, issues)
First occurred: 17:49:34 (5 occurrences)
Last logged: 17:50:53

Unexpected error fetching trakt data: 'title'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 145, in retrieve_data
    data = await gather(
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 110, in fetch_upcomings
    data = await gather(
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 103, in fetch_upcoming
    medias = [trakt_kind.value.model.from_trakt(media) for media in raw_medias]
  File "/config/custom_components/trakt_tv/apis/trakt.py", line 103, in <listcomp>
    medias = [trakt_kind.value.model.from_trakt(media) for media in raw_medias]
  File "/config/custom_components/trakt_tv/models/media.py", line 115, in from_trakt
    name=movie["title"],
KeyError: 'title'
